menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/KeyonYan
    Gitee: https://gitee.com/YanKeyon
    # Rss: /atom.xml


favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2019
